{
  imports = [
    ./boot.nix
    ./sudo.nix
    ./systemd.nix
    ./journald.nix
    ./shell.nix
    ./monitors.nix
    ./nvim.nix
    ./docker.nix
    ./polkit.nix
    ./nvme.nix
    ./keyring.nix
    ./locale.nix
    ./users.nix
    ./env.nix
    ./network
    ./packages.nix
    ./ssh.nix
    ./builders.nix
    ./hotkeys.nix
    ./nix-search-tv.nix
  ];
}
