# .gitlab-ci.yml

# Можно указать образ Docker по умолчанию для всех заданий
# alpine - очень маленький и быстрый образ Linux
image: alpine:latest

stages:
  - test # Определяем один этап (stage)

# Название задания (может быть любым)
simple_check_job:
  stage: test # Указываем, к какому этапу относится это задание
  script:
    - echo "Привет из GitLab CI/CD!"
    - echo "Если ты видишь это сообщение в логах пайплайна, значит CI работает!"
    - ls -la
  # Дополнительно: можно указать, когда запускать задание
  # Например, только для коммитов в ветку main или при создании MR
  # rules:
  #  - if: $CI_COMMIT_BRANCH == "main"