{
  "server" = {
    id = "FZWV52E-4NH5PLX-NPCYQ3L-ETTNYS6-DJ2PUUZ-TMYYMBI-USU2IV7-522RUAI";
  };

  "notebook" = {
    id = "VRMSLNR-XPJJT5E-KZVI6ZA-X7PNWXQ-FQHO4YG-TNTTDME-RH5375D-O7UUCAU";
  };

  "phone" = {
    id = "OJKN7GI-ICOUQGA-YXGEIND-7IUBGVU-SV5FCG5-MCPXVML-5J2QUSE-LZH46AD";
  };

  "pc" = {
    id = "IUJSRXM-YVNRHFR-CYKROGC-PSW4RWS-QQ626ZQ-R7DISEC-UCW3ECW-5B4QLAC";
  };
}
