#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "$0")" && pwd)"
target="$script_dir/../home-manager/modules/opencode/providers/aigate-models.nix"
timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

curl -fsSL "https://api.aigate.shop/v1/models" \
  | jq -r '.data[].id' \
  | LC_ALL=C sort > "$tmp_file"

{
  printf '# Generated by codegen/update-aigate-models.sh at %s\n' "$timestamp"
  printf '{\n'
  while IFS= read -r model; do
    printf '  "%s" = { name = "%s"; };\n' "$model" "$model"
  done < "$tmp_file"
  printf '}\n'
} > "$target"

printf 'Updated %s\n' "$target"
