{ pkgs
, lib
, ...
}:
{
  # Auto-generated by compose2nix.
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."amnezia-wg-easy" = {
    image = "ghcr.io/w0rng/amnezia-wg-easy";
    environmentFiles = [
      "/run/agenix/awg-env"
    ];
    volumes = [
      "amneziawg_etc_wireguard:/etc/wireguard:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--cap-add=SYS_MODULE"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network=host"
    ];
  };
  systemd.services."docker-amnezia-wg-easy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-volume-amneziawg_etc_wireguard.service"
    ];
    requires = [
      "docker-volume-amneziawg_etc_wireguard.service"
    ];
    partOf = [
      "docker-compose-amneziawg-root.target"
    ];
    upheldBy = [
      "docker-volume-amneziawg_etc_wireguard.service"
    ];
    wantedBy = [
      "docker-compose-amneziawg-root.target"
    ];
  };

  # Volumes
  systemd.services."docker-volume-amneziawg_etc_wireguard" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect amneziawg_etc_wireguard || docker volume create amneziawg_etc_wireguard
    '';
    partOf = [ "docker-compose-amneziawg-root.target" ];
    wantedBy = [ "docker-compose-amneziawg-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-amneziawg-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
