# Generated by scripts/codegen/update-aerolink-models.sh at 2026-07-01T15:25:48Z
{
  "claude-haiku-4-5-20251001" = { name = "claude-haiku-4-5-20251001"; };
  "claude-opus-4-6" = { name = "claude-opus-4-6"; };
  "claude-opus-4-7" = { name = "claude-opus-4-7"; };
  "claude-opus-4-8" = { name = "claude-opus-4-8"; };
  "claude-sonnet-4-6" = { name = "claude-sonnet-4-6"; };
}
