#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "$0")" && pwd)"
target="$script_dir/../../home-manager/modules/opencode/providers/pollinations-models.nix"
timestamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
tmp_file="$(mktemp)"
trap 'rm -f "$tmp_file"' EXIT

curl -fsSL "https://gen.pollinations.ai/v1/models" \
  | jq -r '.data[] | select(((.supported_endpoints // []) | index("/v1/chat/completions")) and ((.output_modalities // []) | index("text"))) | .id' \
  | LC_ALL=C sort > "$tmp_file"

{
  printf '# Generated by scripts/codegen/update-pollinations-models.sh at %s\n' "$timestamp"
  printf '{\n'
  while IFS= read -r model; do
    printf '  "%s" = { name = "%s"; };\n' "$model" "$model"
  done < "$tmp_file"
  printf '}\n'
} > "$target"

printf 'Updated %s\n' "$target"
